# Generated by Django 3.0.4 on 2020-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30)),
                ('bloodgrp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=30)),
                ('organ', models.CharField(choices=[('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Eyes', 'Eyes'), ('Money', 'Money')], max_length=30)),
            ],
        ),
    ]
