# Generated by Django 3.0.4 on 2020-03-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='hospshalimar999@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='bloodgrp',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='B+', max_length=30),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Male', max_length=30),
        ),
        migrations.AlterField(
            model_name='donor',
            name='organ',
            field=models.CharField(choices=[('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Eyes', 'Eyes'), ('Money', 'Money'), ('Heart', 'Heart')], default='organ', max_length=30),
        ),
    ]
