# Generated by Django 3.0.4 on 2020-03-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonate', '0002_auto_20200329_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
    ]
