# Generated by Django 3.0.4 on 2020-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organdonate', '0003_auto_20200329_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=500)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Male', max_length=30)),
                ('bloodgrp', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='B+', max_length=30)),
                ('organ', models.CharField(choices=[('Lungs', 'Lungs'), ('Kidney', 'Kidney'), ('Eyes', 'Eyes'), ('Money', 'Money'), ('Heart', 'Heart')], default='organ', max_length=30)),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('availability', models.CharField(default='availability', max_length=5)),
            ],
        ),
    ]
