# Generated by Django 3.0.4 on 2020-03-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organdonate', '0004_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receiver',
        ),
    ]
